//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KepNotificationDev.KEPGonderim {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim")]
    public partial class postaIslemSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sonucKoduField;
        
        private string sonucuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string sonucKodu {
            get {
                return this.sonucKoduField;
            }
            set {
                this.sonucKoduField = value;
                this.RaisePropertyChanged("sonucKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sonucu {
            get {
                return this.sonucuField;
            }
            set {
                this.sonucuField = value;
                this.RaisePropertyChanged("sonucu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim")]
    public partial class postaIcerik : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iletiIcerigiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string iletiIcerigi {
            get {
                return this.iletiIcerigiField;
            }
            set {
                this.iletiIcerigiField = value;
                this.RaisePropertyChanged("iletiIcerigi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim")]
    public partial class authInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string islemYetkiliKoduField;
        
        private string kullaniciAdiField;
        
        private string kullaniciSifresiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string islemYetkiliKodu {
            get {
                return this.islemYetkiliKoduField;
            }
            set {
                this.islemYetkiliKoduField = value;
                this.RaisePropertyChanged("islemYetkiliKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("kullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string kullaniciSifresi {
            get {
                return this.kullaniciSifresiField;
            }
            set {
                this.kullaniciSifresiField = value;
                this.RaisePropertyChanged("kullaniciSifresi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", ConfigurationName="KEPGonderim.KEPGonderim")]
    public interface KEPGonderim {
        
        // CODEGEN: Parameter 'postaKutusu' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(KepNotificationDev.KEPGonderim.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="postaKutusu")]
        KepNotificationDev.KEPGonderim.KEPGonderimiResponse KEPGonderimi(KepNotificationDev.KEPGonderim.KEPGonderimi request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<KepNotificationDev.KEPGonderim.KEPGonderimiResponse> KEPGonderimiAsync(KepNotificationDev.KEPGonderim.KEPGonderimi request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KEPGonderimi", WrapperNamespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", IsWrapped=true)]
    public partial class KEPGonderimi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KepNotificationDev.KEPGonderim.authInput KepKimlikDogrulama;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KepNotificationDev.KEPGonderim.postaIcerik KEPIcerik;
        
        public KEPGonderimi() {
        }
        
        public KEPGonderimi(KepNotificationDev.KEPGonderim.authInput KepKimlikDogrulama, KepNotificationDev.KEPGonderim.postaIcerik KEPIcerik) {
            this.KepKimlikDogrulama = KepKimlikDogrulama;
            this.KEPIcerik = KEPIcerik;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="KEPGonderimiResponse", WrapperNamespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", IsWrapped=true)]
    public partial class KEPGonderimiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://turkkepgw.turkkep.com.tr/KEPWSGonderim", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public KepNotificationDev.KEPGonderim.postaIslemSonuc postaKutusu;
        
        public KEPGonderimiResponse() {
        }
        
        public KEPGonderimiResponse(KepNotificationDev.KEPGonderim.postaIslemSonuc postaKutusu) {
            this.postaKutusu = postaKutusu;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KEPGonderimChannel : KepNotificationDev.KEPGonderim.KEPGonderim, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KEPGonderimClient : System.ServiceModel.ClientBase<KepNotificationDev.KEPGonderim.KEPGonderim>, KepNotificationDev.KEPGonderim.KEPGonderim {
        
        public KEPGonderimClient() {
        }
        
        public KEPGonderimClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KEPGonderimClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KEPGonderimClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KEPGonderimClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KepNotificationDev.KEPGonderim.KEPGonderimiResponse KepNotificationDev.KEPGonderim.KEPGonderim.KEPGonderimi(KepNotificationDev.KEPGonderim.KEPGonderimi request) {
            return base.Channel.KEPGonderimi(request);
        }
        
        public KepNotificationDev.KEPGonderim.postaIslemSonuc KEPGonderimi(KepNotificationDev.KEPGonderim.authInput KepKimlikDogrulama, KepNotificationDev.KEPGonderim.postaIcerik KEPIcerik) {
            KepNotificationDev.KEPGonderim.KEPGonderimi inValue = new KepNotificationDev.KEPGonderim.KEPGonderimi();
            inValue.KepKimlikDogrulama = KepKimlikDogrulama;
            inValue.KEPIcerik = KEPIcerik;
            KepNotificationDev.KEPGonderim.KEPGonderimiResponse retVal = ((KepNotificationDev.KEPGonderim.KEPGonderim)(this)).KEPGonderimi(inValue);
            return retVal.postaKutusu;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KepNotificationDev.KEPGonderim.KEPGonderimiResponse> KepNotificationDev.KEPGonderim.KEPGonderim.KEPGonderimiAsync(KepNotificationDev.KEPGonderim.KEPGonderimi request) {
            return base.Channel.KEPGonderimiAsync(request);
        }
        
        public System.Threading.Tasks.Task<KepNotificationDev.KEPGonderim.KEPGonderimiResponse> KEPGonderimiAsync(KepNotificationDev.KEPGonderim.authInput KepKimlikDogrulama, KepNotificationDev.KEPGonderim.postaIcerik KEPIcerik) {
            KepNotificationDev.KEPGonderim.KEPGonderimi inValue = new KepNotificationDev.KEPGonderim.KEPGonderimi();
            inValue.KepKimlikDogrulama = KepKimlikDogrulama;
            inValue.KEPIcerik = KEPIcerik;
            return ((KepNotificationDev.KEPGonderim.KEPGonderim)(this)).KEPGonderimiAsync(inValue);
        }
    }
}
